name: Automated Sync to Pascolab

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Sync to Pascolab
        env:
          SYNC_TOKEN: ${{ secrets.PASCOLAB_SYNC_TOKEN }}
        run: |
          git remote add pascolab https://x-access-token:${SYNC_TOKEN}@github.com/pascolab/pascolab.git
          git push pascolab main --force