name: Automated Sync to Pascolab

on:
  push:

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: 
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add Pascolab Remote
        run: 
          git remote remove pascolab || true
          git remote add pascolab https://x-access-token:${{ secrets.PASCOLAB_SYNC_TOKEN }}@github.com/pascolab/pascolab.git

      - name: Sync All Branches
      run: 
        git push pascolab --all


      - name: Sync Tags
        run: 
          git push pascolab --tags
